//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/PseudoThrow.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PseudoThrow: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PseudoThrow()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PseudoThrow"",
    ""maps"": [
        {
            ""name"": ""PsuedoThrow"",
            ""id"": ""1de7968e-aeda-4fb6-8785-0ca091ed4d8c"",
            ""actions"": [
                {
                    ""name"": ""ClickTHrow"",
                    ""type"": ""Button"",
                    ""id"": ""a4b42049-5629-4354-aedd-585a4522adbb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7ac6fa9b-ffe6-4685-8206-4fef35598b6d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickTHrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PsuedoThrow
        m_PsuedoThrow = asset.FindActionMap("PsuedoThrow", throwIfNotFound: true);
        m_PsuedoThrow_ClickTHrow = m_PsuedoThrow.FindAction("ClickTHrow", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PsuedoThrow
    private readonly InputActionMap m_PsuedoThrow;
    private List<IPsuedoThrowActions> m_PsuedoThrowActionsCallbackInterfaces = new List<IPsuedoThrowActions>();
    private readonly InputAction m_PsuedoThrow_ClickTHrow;
    public struct PsuedoThrowActions
    {
        private @PseudoThrow m_Wrapper;
        public PsuedoThrowActions(@PseudoThrow wrapper) { m_Wrapper = wrapper; }
        public InputAction @ClickTHrow => m_Wrapper.m_PsuedoThrow_ClickTHrow;
        public InputActionMap Get() { return m_Wrapper.m_PsuedoThrow; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PsuedoThrowActions set) { return set.Get(); }
        public void AddCallbacks(IPsuedoThrowActions instance)
        {
            if (instance == null || m_Wrapper.m_PsuedoThrowActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PsuedoThrowActionsCallbackInterfaces.Add(instance);
            @ClickTHrow.started += instance.OnClickTHrow;
            @ClickTHrow.performed += instance.OnClickTHrow;
            @ClickTHrow.canceled += instance.OnClickTHrow;
        }

        private void UnregisterCallbacks(IPsuedoThrowActions instance)
        {
            @ClickTHrow.started -= instance.OnClickTHrow;
            @ClickTHrow.performed -= instance.OnClickTHrow;
            @ClickTHrow.canceled -= instance.OnClickTHrow;
        }

        public void RemoveCallbacks(IPsuedoThrowActions instance)
        {
            if (m_Wrapper.m_PsuedoThrowActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPsuedoThrowActions instance)
        {
            foreach (var item in m_Wrapper.m_PsuedoThrowActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PsuedoThrowActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PsuedoThrowActions @PsuedoThrow => new PsuedoThrowActions(this);
    public interface IPsuedoThrowActions
    {
        void OnClickTHrow(InputAction.CallbackContext context);
    }
}
